from tkinter import *
a=Tk()
a.title("Untitled - Notepad")
a.geometry("500x500+100+100")
m1=Menu()
l1=Menu()
l1.add_command(label="New           Ctrl+N")
l1.add_command(label="New Window    Ctrl+Shift+N")
l1.add_command(label="Open...       Ctrl+O")
l1.add_command(label="Save          Ctrl+S")
l1.add_command(label="Save As...    Ctrl+Shift+S")
l1.add_command(label="Page Setup...")
l1.add_command(label="Print...      Ctrl+P")
l1.add_command(label="Exit  ")

l2=Menu()
l2.add_command(label="Undo  Ctrl+Z")
l2.add_command(label="Cut   Ctrl+X")
l2.add_command(label="Copy  Ctrl+C")
l2.add_command(label="Paste Ctrl+V")
l2.add_command(label="Delete    Del")
l2.add_command(label="Search with Bing...   Ctrl+E")
l2.add_command(label="Find...   Ctrl+F")
l2.add_command(label="Find Next     F3")
l2.add_command(label="Find Previous Shift+F3")
l2.add_command(label="Replace...    Ctrl+H")
l2.add_command(label="Go To...  Ctrl+G")
l2.add_command(label="Select All    Ctrl+A")
l2.add_command(label="Time/Date     F5")

l3=Menu()
l3.add_command(label="Word Wrap")
l3.add_command(label="Font")
l4=Menu()
l4.add_command(label="Zoom")
l4.add_command(label="Status Bar")
l5=Menu()
l5.add_command(label="View Help")
l5.add_command(label="Send Feedback")
l5.add_command(label="About Notepad")

m1.add_cascade(label="File",menu=l1)
m1.add_cascade(label="Edit",menu=l2)
m1.add_cascade(label="Format",menu=l3)
m1.add_cascade(label="View",menu=l4)
m1.add_cascade(label="Help",menu=l5)
a.config(menu=m1)
e = Text(a, width=60,height=50)
e.grid(row=0, column=0, padx=10, pady=10)
a.mainloop()